export enum ErrorCode {

    NOERROR = 0,

    // misc errors
    ERROR = 100,

    PARAMETER_INVALID,

    QR_DECODE_ERROR,

    SHC_DECODE_ERROR,
    SHC_ENCODE_ERROR,
    SHC_FORMAT_ERROR,

    JWS_COMPACT_DECODE_ERROR,
    JWS_COMPACT_ENCODE_ERROR,
    JWS_COMPACT_FORMAT_ERROR,
    JWS_COMPACT_MISSING,

    JWS_MISSING,
    JWS_MISSING_HEADER,
    JWS_MISSING_PAYLOAD,
    JWS_MISSING_SIGNATURE,
    JWS_ENCODE_FAIL,

    JWS_HEADER_DECODE_FAIL,
    JWS_HEADER_ENCODE_FAIL,
    JWS_HEADER_ERROR,
    JWS_HEADER_GENERATE_FAIL,

    JWS_SIGNATURE_DECODE_FAIL,
    JWS_SIGNATURE_ENCODE_FAIL,
    JWS_SIGNATURE_MISSING,
    JWS_SIGNATURE_NO_PUBLIC_KEYS,
    JWS_SIGNATURE_FORMAT_ERROR,

    JWS_PAYLOAD_DECODE_ERROR,
    JWS_PAYLOAD_ENCODE_ERROR,
    JWS_PAYLOAD_ERROR,
    JWS_PAYLOAD_ISS_MISSING,
    JWS_PAYLOAD_NOT_DEFLATED,

    SIGNATURE_INVALID,

    DIRECTORY_ERROR,
    DIRECTORY_ISSUER_MISSING_ISS,
    DIRECTORY_ISSUER_INVALID_PROPERTY,
    DIRECTORY_MISSING,
    DIRECTORY_ISSUER_NOT_FOUND,
    DIRECTORY_KEY_NOT_FOUND,
    DIRECTORY_SCHEMA_ERROR,

    JWK_UNEXPECTED_PROPERTY,
    JWK_INVALID_PROPERTY,
    JWK_INCORRECT_KID,

    CRYPTO_FAILURE,

    DOWNLOAD_FAILED,

    FHIR_VALIDATION_ERROR,
}
