export enum ErrorCode {

    NOERROR = 0,

    // misc errors
    ERROR = 100,

    QR_DECODE_ERROR,
    INVALID_COMPACT_JWS,
    PAYLOAD_NOT_DEFLATED,
    JWS_HEADER_DECODE_FAIL,
    JWS_HEADER_ERROR,
    JWS_PAYLOAD_ERROR,
    SIGNATURE_FORMAT_ERROR,
    SHC_DECODE_ERROR,
    INVALID_SIGNATURE
}
